#!/bin/bash

source ../../../setenv.sh

mpirun -n 1 pampa input.pmp -ksp_type cg | grep "Solution time: "; echo "cg"
mpirun -n 1 pampa input.pmp -ksp_type groppcg | grep "Solution time: "; echo "groppcg"
mpirun -n 1 pampa input.pmp -ksp_type pipecg | grep "Solution time: "; echo "pipecg"
mpirun -n 1 pampa input.pmp -ksp_type pipecgrr | grep "Solution time: "; echo "pipecgrr"
mpirun -n 1 pampa input.pmp -ksp_type cgne | grep "Solution time: "; echo "cgne"
mpirun -n 1 pampa input.pmp -ksp_type nash | grep "Solution time: "; echo "nash"
mpirun -n 1 pampa input.pmp -ksp_type stcg | grep "Solution time: "; echo "stcg"
mpirun -n 1 pampa input.pmp -ksp_type gltr | grep "Solution time: "; echo "gltr"
mpirun -n 1 pampa input.pmp -ksp_type fcg | grep "Solution time: "; echo "fcg"
mpirun -n 1 pampa input.pmp -ksp_type pipefcg | grep "Solution time: "; echo "pipefcg"
mpirun -n 1 pampa input.pmp -ksp_type gmres | grep "Solution time: "; echo "gmres"
mpirun -n 1 pampa input.pmp -ksp_type pipefgmres | grep "Solution time: "; echo "pipefgmres"
mpirun -n 1 pampa input.pmp -ksp_type fgmres | grep "Solution time: "; echo "fgmres"
mpirun -n 1 pampa input.pmp -ksp_type lgmres | grep "Solution time: "; echo "lgmres"
mpirun -n 1 pampa input.pmp -ksp_type dgmres | grep "Solution time: "; echo "dgmres"
mpirun -n 1 pampa input.pmp -ksp_type pgmres | grep "Solution time: "; echo "pgmres"
mpirun -n 1 pampa input.pmp -ksp_type tcqmr | grep "Solution time: "; echo "tcqmr"
mpirun -n 1 pampa input.pmp -ksp_type bcgs | grep "Solution time: "; echo "bcgs"
mpirun -n 1 pampa input.pmp -ksp_type ibcgs | grep "Solution time: "; echo "ibcgs"
mpirun -n 1 pampa input.pmp -ksp_type qmrcgs | grep "Solution time: "; echo "qmrcgs"
mpirun -n 1 pampa input.pmp -ksp_type fbcgs | grep "Solution time: "; echo "fbcgs"
mpirun -n 1 pampa input.pmp -ksp_type fbcgsr | grep "Solution time: "; echo "fbcgsr"
mpirun -n 1 pampa input.pmp -ksp_type bcgsl | grep "Solution time: "; echo "bcgsl"
mpirun -n 1 pampa input.pmp -ksp_type pipebcgs | grep "Solution time: "; echo "pipebcgs"
mpirun -n 1 pampa input.pmp -ksp_type cgs | grep "Solution time: "; echo "cgs"
mpirun -n 1 pampa input.pmp -ksp_type tfqmr | grep "Solution time: "; echo "tfqmr"
mpirun -n 1 pampa input.pmp -ksp_type cr | grep "Solution time: "; echo "cr"
mpirun -n 1 pampa input.pmp -ksp_type pipecr | grep "Solution time: "; echo "pipecr"
mpirun -n 1 pampa input.pmp -ksp_type lsqr | grep "Solution time: "; echo "lsqr"
mpirun -n 1 pampa input.pmp -ksp_type preonly | grep "Solution time: "; echo "preonly"
mpirun -n 1 pampa input.pmp -ksp_type none | grep "Solution time: "; echo "none"
mpirun -n 1 pampa input.pmp -ksp_type qcg | grep "Solution time: "; echo "qcg"
mpirun -n 1 pampa input.pmp -ksp_type bicg | grep "Solution time: "; echo "bicg"
mpirun -n 1 pampa input.pmp -ksp_type minres | grep "Solution time: "; echo "minres"
mpirun -n 1 pampa input.pmp -ksp_type symmlq | grep "Solution time: "; echo "symmlq"
mpirun -n 1 pampa input.pmp -ksp_type lcd | grep "Solution time: "; echo "lcd"
mpirun -n 1 pampa input.pmp -ksp_type python | grep "Solution time: "; echo "python"
mpirun -n 1 pampa input.pmp -ksp_type gcr | grep "Solution time: "; echo "gcr"
mpirun -n 1 pampa input.pmp -ksp_type pipegcr | grep "Solution time: "; echo "pipegcr"
mpirun -n 1 pampa input.pmp -ksp_type tsirm | grep "Solution time: "; echo "tsirm"
mpirun -n 1 pampa input.pmp -ksp_type cgls | grep "Solution time: "; echo "cgls"
mpirun -n 1 pampa input.pmp -ksp_type fetidp | grep "Solution time: "; echo "fetidp"
mpirun -n 1 pampa input.pmp -ksp_type hpddm | grep "Solution time: "; echo "hpddm"
